import pandas as pd
import re

# 1. Load the CSV generated by your main script
csv_file = 'all_users_explanations_metrics.csv'
df = pd.read_csv(csv_file)


# =========================================================
# STEP 1: Find 1-sentence explanations starting with "Since you liked"
# =========================================================
def find_single_sentence_target(text):
    text = str(text).strip()

    # Condition A: It must start with "Since you liked"
    #if not text.startswith("Since you liked"):
        #return False

    # Condition B: It must be exactly ONE sentence.
    chunks = [chunk for chunk in re.split(r'[.!?]+', text) if chunk.strip()]
    return len(chunks) == 1


# Apply the first filter
step1_mask = df['Explanation Text (LLM)'].apply(find_single_sentence_target)
step1_df = df[step1_mask]

print(f"Step 1: Found {len(step1_df)} / {len(df)} single-sentence explanations starting with 'Since you liked'.")

# =========================================================
# STEP 2: From those results, keep only the ones with valid endings
# =========================================================
valid_endings = ('.', '!', '?', '"', "'", '”', '’')

step2_mask = step1_df['Explanation Text (LLM)'].astype(str).str.strip().str.endswith(valid_endings)

# We use .copy() here to avoid Pandas "SettingWithCopyWarning" when adding the word count column later
final_df = step1_df[step2_mask].copy()

print(f"Step 2: Narrowed down to {len(final_df)} explanations that also have valid endings.\n")

# =========================================================
# STEP 3: Print normal examples and the Top 5 longest ones
# =========================================================
if len(final_df) > 0:
    print("Here are the first 5 perfect examples:")
    for text in final_df['Explanation Text (LLM)'].head(5):
        print(f"- {text}\n")

    # --- NEW CODE: Calculate words, sort, and print top 5 longest ---

    # Create a new column with the word count for each explanation
    final_df['Word Count'] = final_df['Explanation Text (LLM)'].apply(lambda x: len(str(x).split()))

    # Sort the dataframe by the 'Word Count' column in descending order (longest first)
    top_5_longest = final_df.sort_values(by='Word Count', ascending=False).head(5)

    print("=========================================================")
    print("🏆 Top 5 Longest Explanations (by Word Count)")
    print("=========================================================")
    for index, row in top_5_longest.iterrows():
        print(f"[{row['Word Count']} words] - {row['Explanation Text (LLM)']}\n")


    # Optional: Save these specific rows to a new CSV (it will now include the Word Count column!)
    final_df.to_csv('perfect_single_sentences.csv', index=False)
    print("Saved all perfect matches to 'perfect_single_sentences.csv'")

    print(f"\n==================================================")
    print(f" ⚖️ FINAL LLM JUDGE AVERAGES")
    print(f"==================================================")
    print(f"Mean Fluency: {final_df['Judge_Fluency'].mean():.2f} / 1")
    print(f"Mean Relevance: {final_df['Judge_Relevance'].mean():.2f} / 1")
    print(f"Mean Faithfulness: {final_df['Judge_Faithfulness'].mean():.2f} / 1")
    print(f"==================================================\n")

    print("\n==================================================")
    print(" 🗣️  SIMULATED USER-INTERVIEW AVERAGES")
    print(" (Mohseni et al. dimensions; 1-5 Likert scale)")
    print("==================================================")
    print(f"Mean Mental-Model Clarity: {final_df['Sim_MentalModel'].mean():.2f} / 5")
    print(f"Mean Satisfaction:          {final_df['Sim_Satisfaction'].mean():.2f} / 5")
    print(f"Mean Clarity:               {final_df['Sim_Clarity'].mean():.2f} / 5")
    print(f"Mean Trust:                 {final_df['Sim_Trust'].mean():.2f} / 5")
    print(f"Mean Persuasion:            {final_df['Sim_Persuasion'].mean():.2f} / 5")
    watch_rate = final_df["Sim_WouldWatch"].mean()
    print(f"Would-Watch Rate:           {watch_rate:.2%}")
    print("==================================================\n")
